import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {mkdtemp,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
process.env.APP_MODE='local';process.env.LOCAL_DATA_DIR=await mkdtemp(path.join(os.tmpdir(),'studio-p0-'));process.env.APP_URL='http://localhost:4173';process.env.TRUSTED_ORIGINS='http://localhost:4173';process.env.BETTER_AUTH_SECRET=randomBytes(32).toString('hex');process.env.AI_ENABLED='false';delete process.env.DATABASE_URL;
const {getAuth}=await import('../lib/server/auth');const {handle}=await import('../lib/server/service');const {getDb}=await import('../lib/server/db');
const results:{name:string,status:string}[]=[];
async function test(name:string,fn:()=>Promise<void>){await fn();results.push({name,status:'PASS'});console.log('PASS',name)}
const origin='http://localhost:4173';
async function signup(name:string){const auth=await getAuth();const r=await auth.handler(new Request(origin+'/api/auth/sign-up/email',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify({email:name+'@example.test',password:'Test-password-2026!',name})}));assert.equal(r.status,200,await r.clone().text());const cookie=r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');assert(cookie);const body:any=await r.json();return {cookie,userId:body.user.id}}
async function call(cookie:string,url:string,method='GET',body?:any,key?:string){const res=await handle(new Request(origin+'/api/'+url,{method,headers:{cookie,origin,...(!(body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)}));const text=await res.text();let data:any;try{data=JSON.parse(text)}catch{data=text}return {status:res.status,data}}
async function ok(cookie:string,url:string,method='GET',body?:any,key?:string){const r=await call(cookie,url,method,body,key);assert(r.status>=200&&r.status<300,JSON.stringify(r));return r.data}
let A:any,B:any,wa:any,wb:any,aa:any,ab:any,oa:any,ob:any,c1:any,c2:any,file:any;
await test('가입: 별도 계정 A/B와 독립 세션 생성',async()=>{A=await signup('company-a');B=await signup('company-b');assert.notEqual(A.cookie,B.cookie)});
await test('작업공간 생성·전환 데이터',async()=>{wa=await ok(A.cookie,'workspaces','POST',{name:'A Company'});wb=await ok(B.cookie,'workspaces','POST',{name:'B Company'});const extra=await ok(A.cookie,'workspaces','POST',{name:'A second'});const me=await ok(A.cookie,'me');assert.equal(me.workspaces.length,2);assert(me.workspaces.some((w:any)=>w.id===extra.id));assert(!me.workspaces.some((w:any)=>w.id===wb.id))});
await test('고객군·제품 저장과 다국어 원문',async()=>{aa=await ok(A.cookie,`workspaces/${wa.id}/audiences`,'POST',{data:{name:'중장년',problem:'운동 방법을 모름',outcome:'규칙 배우기'}});ab=await ok(B.cookie,`workspaces/${wb.id}/audiences`,'POST',{data:{name:'B audience'}});const base={kind:'service',name:'공원구 입문 체험',summary:'장비 대여와 기본 규칙 안내',audience_id:aa.id,features:'장비 대여',how:'예약 후 현장 체험',benefits:'장비 구매 전 체험 가능',cta:'일정 문의하기',price:'20,000',currency:'KRW',translations:{zh:{name:'公园球入门体验',summary:'提供器材租借与基本规则讲解。',audience:'中老年初学者',problem:'不了解运动规则',features:'器材租借',benefits:'购买器材前可以先体验',cta:'咨询体验时间'},en:{name:'Parkball introduction',summary:'Equipment rental and basic rules.',audience:'Adult beginners',features:'Equipment rental',cta:'Ask about dates'}}};oa=await ok(A.cookie,`workspaces/${wa.id}/offerings`,'POST',{data:base});ob=await ok(B.cookie,`workspaces/${wb.id}/offerings`,'POST',{data:{...base,name:'B Product',audience_id:ab.id}});assert.equal((await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`)).data.price,'20,000')});
await test('다른 고객 Workspace/제품 GET·PUT 접근 차단',async()=>{assert.equal((await call(B.cookie,`workspaces/${wa.id}/offerings/${oa.id}`)).status,404);assert.equal((await call(B.cookie,`workspaces/${wb.id}/offerings/${oa.id}`)).status,404);assert.equal((await call(B.cookie,`workspaces/${wa.id}/offerings/${oa.id}`,'PUT',{data:oa.data,revision:1})).status,404)});
await test('교차 Workspace 외래키 연결 차단',async()=>{assert.equal((await call(B.cookie,`workspaces/${wb.id}/offerings`,'POST',{data:{...ob.data,audience_id:aa.id}})).status,404);const db=await getDb();await assert.rejects(()=>db.query('INSERT INTO offering(id,workspace_id,audience_id,data) VALUES($1,$2,$3,$4)',[randomUUID(),wb.id,aa.id,'{}']))});
const settings=async(wid:string,cookie:string,off:any,aud:any,overrides:any={})=>({offering_id:off.id,audience_id:aud.id,objective:'인지',format:'page',language:'ko',tone:'professional',length:'standard',cta:'',source_revision:(await ok(cookie,'workspaces/'+wid)).revision,...overrides});
await test('한국어 제품 페이지·중국어 SNS 생성 및 영구 저장',async()=>{c1=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,A.cookie,oa,aa),randomUUID());c2=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,A.cookie,oa,aa,{format:'social',language:'zh',objective:'문의'}),randomUUID());assert(c1.latest.body.includes('장비 대여'));assert(c1.latest.body.includes('20,000'));assert(c2.latest.body.includes('公园球'));assert(c2.latest.body.includes('咨询体验时间'));assert(c1.latest.annotations.used_source_ids.length>=3);assert.equal(c1.latest.annotations.mode,'기본 문안');assert.equal((await ok(A.cookie,`workspaces/${wa.id}/contents`)).length,2)});
await test('근거 없는 매출 50% 증가 주장 제외',async()=>{const c=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,A.cookie,oa,aa,{requested_claim:'매출 50% 증가'}),randomUUID());assert(!c.latest.body.includes('50%'));assert(c.latest.annotations.unsupported_claims.includes('매출 50% 증가'))});
await test('본문 속 위험 주장과 미확인 증거도 제외',async()=>{const altered=await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`,'PUT',{revision:oa.revision,data:{...oa.data,benefits:'매출 50% 증가',proofs:[{id:'false-proof',statement:'매출 50% 증가',source:'https://example.test/unverified',status:'unverified',verified_at:''}]}});oa=altered;const c=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,A.cookie,oa,aa),randomUUID());assert(!c.latest.body.includes('50%'));assert(c.latest.annotations.unsupported_claims.includes('매출 50% 증가'))});
await test('같은 요청 재전송 및 동시 요청은 콘텐츠 한 개 생성',async()=>{const key=randomUUID(),s=await settings(wa.id,A.cookie,oa,aa,{format:'email',language:'en'});const rs=await Promise.all([call(A.cookie,`workspaces/${wa.id}/generations`,'POST',s,key),call(A.cookie,`workspaces/${wa.id}/generations`,'POST',s,key)]);assert(rs.every(r=>[200,201,202].includes(r.status)));const again=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',s,key);const db=await getDb();assert.equal((await db.query('SELECT count(*)::int AS n FROM generation_run WHERE workspace_id=$1 AND idempotency_key=$2',[wa.id,key])).rows[0].n,1);assert(again.id);assert.equal((await call(A.cookie,`workspaces/${wa.id}/generations`,'POST',{...s,format:'ad'},key)).status,409)});
await test('가격 변경: 과거 스냅샷 보존·stale 표시·새 가격 반영',async()=>{oa=await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`,'PUT',{revision:oa.revision,data:{...oa.data,price:'30,000',benefits:'장비 구매 전 체험 가능'}});const old=await ok(A.cookie,`workspaces/${wa.id}/contents/${c1.id}`);assert.equal(old.stale,true);assert.equal(old.source_snapshot.offering.data.price,'20,000');assert(old.latest.body.includes('20,000'));const fresh=await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,A.cookie,oa,aa),randomUUID());assert(fresh.latest.body.includes('30,000'));assert.equal(fresh.stale,false);assert((await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}/versions`)).length>=3)});
await test('수정 경쟁 충돌·오래된 원천 버전 생성 차단',async()=>{assert.equal((await call(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`,'PUT',{revision:1,data:oa.data})).status,409);assert.equal((await call(A.cookie,`workspaces/${wa.id}/generations`,'POST',{...await settings(wa.id,A.cookie,oa,aa),source_revision:1},randomUUID())).status,409)});
await test('편집 버전 저장·검토 상태·이전 버전 보존·내보내기',async()=>{const c=await ok(A.cookie,`workspaces/${wa.id}/contents/${c1.id}`,'PUT',{title:'수정 제목',body:'직접 검토한 소개문',version:1,status:'reviewed'});assert.equal(c.current_version,2);assert.equal(c.versions.length,2);assert.equal(c.status,'reviewed');assert(c.versions[1].body.includes('20,000'));assert.equal((await ok(A.cookie,`workspaces/${wa.id}/contents/${c1.id}/export`)),'직접 검토한 소개문');const exported=await ok(A.cookie,`workspaces/${wa.id}/contents/${c1.id}/export?format=json`);assert.equal(exported.source_snapshot.offering.data.price,'20,000');assert.equal((await call(A.cookie,`workspaces/${wa.id}/contents/${c1.id}`,'PUT',{title:'충돌',body:'충돌',version:1})).status,409)});
await test('파일 업로드·사적 다운로드·다른 고객 파일/초안 접근 차단',async()=>{const f=new FormData();f.append('file',new File(['사용자가 제공한 제품 설명'], 'proof.txt',{type:'text/plain'}));f.append('rights_note','직접 작성');file=await ok(A.cookie,`workspaces/${wa.id}/assets`,'POST',f);assert.equal(file.status,'ready');assert.equal(await ok(A.cookie,`workspaces/${wa.id}/assets/${file.id}/download`),'사용자가 제공한 제품 설명');for(const route of [`assets/${file.id}`,`assets/${file.id}/download`,`contents/${c1.id}`,`contents/${c1.id}/export`,`contents/${c1.id}/versions`]){assert.equal((await call(B.cookie,`workspaces/${wa.id}/`+route)).status,404);assert.equal((await call(B.cookie,`workspaces/${wb.id}/`+route)).status,404)}});
await test('불량 업로드 거절·PDF 격리·정상 재시도',async()=>{const bad=new FormData();bad.append('file',new File(['not png'],'fake.png',{type:'image/png'}));assert.equal((await call(A.cookie,`workspaces/${wa.id}/assets`,'POST',bad)).status,400);const pdf=new FormData();pdf.append('file',new File(['%PDF-1.4\nquarantine test'],'test.pdf',{type:'application/pdf'}));const p=await ok(A.cookie,`workspaces/${wa.id}/assets`,'POST',pdf);assert.equal(p.status,'quarantined');assert.equal((await call(A.cookie,`workspaces/${wa.id}/assets/${p.id}/download`)).status,423);assert.equal((await ok(A.cookie,`workspaces/${wa.id}/assets`)).length,2)});
await test('AI 실패 기록·원천 보존·재시도 성공',async()=>{process.env.AI_ENABLED='true';delete process.env.AI_PROVIDER_URL;const before=await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`);const s=await settings(wa.id,A.cookie,oa,aa);assert.equal((await call(A.cookie,`workspaces/${wa.id}/generations`,'POST',s,randomUUID())).status,502);process.env.AI_ENABLED='false';assert.deepEqual((await ok(A.cookie,`workspaces/${wa.id}/offerings/${oa.id}`)).data,before.data);assert((await ok(A.cookie,`workspaces/${wa.id}/generations`,'POST',s,randomUUID())).id)});
await test('Viewer 권한: 읽기 허용, 저장·생성·파일 업로드 거절',async()=>{const db=await getDb();await db.query("INSERT INTO membership(workspace_id,user_id,role) VALUES($1,$2,'viewer')",[wa.id,B.userId]);assert.equal((await call(B.cookie,`workspaces/${wa.id}/offerings`)).status,200);assert.equal((await call(B.cookie,`workspaces/${wa.id}/offerings/${oa.id}`,'PUT',{revision:oa.revision,data:oa.data})).status,403);assert.equal((await call(B.cookie,`workspaces/${wa.id}/generations`,'POST',await settings(wa.id,B.cookie,oa,aa),randomUUID())).status,403);await db.query('DELETE FROM membership WHERE workspace_id=$1 AND user_id=$2',[wa.id,B.userId])});
await test('비인증/외부 Origin 요청 차단',async()=>{assert.equal((await call('',`workspaces/${wa.id}/contents`)).status,401);const r=await handle(new Request(origin+'/api/workspaces',{method:'POST',headers:{origin:'https://evil.example',cookie:A.cookie,'Content-Type':'application/json'},body:JSON.stringify({name:'forged'})}));assert.equal(r.status,403)});
let wp:any,ap:any,op:any,cp:any,photo:any,media:any;
await test('P1 채널 템플릿·제안서·영상 대본·3개 언어',async()=>{
 wp=await ok(A.cookie,'workspaces','POST',{name:'P1 examples'});ap=await ok(A.cookie,`workspaces/${wp.id}/audiences`,'POST',{data:aa.data});op=await ok(A.cookie,`workspaces/${wp.id}/offerings`,'POST',{data:{...oa.data,audience_id:ap.id}});
 for(const [format,channel,language] of [['proposal','website','ko'],['video_script','instagram','zh'],['social','wechat','zh'],['email','email','en'],['social','linkedin','en']]){
  const content=await ok(A.cookie,`workspaces/${wp.id}/generations`,'POST',await settings(wp.id,A.cookie,op,ap,{format,channel,language}),randomUUID());assert(content.latest.body.length>20);assert.equal(content.settings.channel,channel);assert.equal(content.latest.annotations.template_version,'channels-v2');assert(content.latest.body.includes(language==='zh'?'公园球':language==='en'?'Parkball':'공원구'));cp=content;
 }
 assert.equal((await call(A.cookie,`workspaces/${wp.id}/generations`,'POST',await settings(wp.id,A.cookie,op,ap,{format:'page',channel:'instagram'}),randomUUID())).status,400);
 const catalog=await ok(A.cookie,`workspaces/${wp.id}/templates`);assert(catalog.channels.wechat);
});
await test('P1 다국어 원문 누락 안내·번역을 이용한 가격/근거 덮어쓰기 방지',async()=>{
 const {fallback}=await import('../lib/server/generator');const source=structuredClone(cp.source_snapshot);source.offering.data.translations.zh.price='1';source.offering.data.translations.zh.proofs=[{statement:'매출 50% 증가',status:'verified'}];
 const out=fallback(source,{...cp.settings,language:'zh',format:'page',channel:'website'});assert(out.sections.some((s:any)=>s.body.includes('30,000')));assert(!JSON.stringify(out.sections).includes('50%'));assert(out.missing_facts.some(s=>s.includes('번역 원문 미등록')));
});
await test('P1 승인 상태 전이·owner 전용 승인·버전 고정',async()=>{
 const db=await getDb();await db.query("INSERT INTO membership(workspace_id,user_id,role) VALUES($1,$2,'editor')",[wp.id,B.userId]);
 const base=`workspaces/${wp.id}/contents/${cp.id}`;
 assert.equal((await call(A.cookie,base+'/review','POST',{action:'approve',version:1})).status,409);
 cp=await ok(B.cookie,base+'/review','POST',{action:'submit',version:1});assert.equal(cp.workflow.state,'pending');
 assert.equal((await call(B.cookie,base+'/review','POST',{action:'approve',version:1})).status,403);
 assert.equal((await call(A.cookie,base+'/review','POST',{action:'request_changes',version:1})).status,400);
 cp=await ok(A.cookie,base+'/review','POST',{action:'request_changes',version:1,note:'CTA를 확인해 주세요.'});assert.equal(cp.workflow.state,'changes_requested');
 cp=await ok(B.cookie,base+'/review','POST',{action:'submit',version:1});
 cp=await ok(A.cookie,base+'/review','POST',{action:'approve',version:1});assert.equal(cp.workflow.state,'approved');assert.equal(cp.current_version,2);assert.equal(cp.versions[1].version,1);assert.equal(cp.latest.annotations.approved,true);
 assert.equal((await call(A.cookie,base+'/review','POST',{action:'approve',version:1})).status,409);
});
await test('P1 승인 이후 편집은 별도 초안·승인 이력 보존',async()=>{
 cp=await ok(B.cookie,`workspaces/${wp.id}/contents/${cp.id}`,'PUT',{version:2,title:'공원구 입문 체험 · 예시',body:'공원구 입문 체험 · 예시\n\n장비 대여와 기본 규칙 안내\n\n체험 일정 문의하기'});
 assert.equal(cp.current_version,3);assert.equal(cp.workflow.state,'draft');assert.equal(cp.latest.annotations.approved,false);assert(cp.reviews.some((e:any)=>e.action==='approve'&&e.version===2));assert(cp.versions.find((v:any)=>v.version===2).annotations.approved);
});
await test('P1 원천 변경 후 승인 차단·복제는 원천과 승인 상태 분리',async()=>{
 op=await ok(A.cookie,`workspaces/${wp.id}/offerings/${op.id}`,'PUT',{revision:op.revision,data:{...op.data,price:'40,000'}});
 await ok(B.cookie,`workspaces/${wp.id}/contents/${cp.id}/review`,'POST',{action:'submit',version:3});
 assert.equal((await call(A.cookie,`workspaces/${wp.id}/contents/${cp.id}/review`,'POST',{action:'approve',version:3})).status,409);
 const copy=await ok(B.cookie,`workspaces/${wp.id}/contents/${cp.id}/reuse`,'POST',{version:2});assert.notEqual(copy.id,cp.id);assert.equal(copy.current_version,1);assert.equal(copy.workflow.state,'draft');assert.equal(copy.latest.annotations.approved,false);assert.equal(copy.source_snapshot.offering.data.price,'30,000');assert(copy.stale);assert.equal(copy.latest.annotations.reused_from.version,2);
});
await test('P1 실제 사진 업로드·카드 제작·중복 요청·사적 다운로드',async()=>{
 const sharp=(await import('sharp')).default;const bytes=await sharp({create:{width:1200,height:800,channels:3,background:'#a5b6cc'}}).png().toBuffer();
 const f=new FormData();f.append('file',new File([new Uint8Array(bytes)],'example-photo.png',{type:'image/png'}));f.append('rights_note','자동 테스트용 단색 이미지 · 실제 제품 사진 아님');photo=await ok(A.cookie,`workspaces/${wp.id}/assets`,'POST',f);
 const payload={content_id:cp.id,version:3,asset_id:photo.id,kind:'cards',scenes:['공원구 입문 체험 · 예시','장비 대여와 기본 규칙 안내','체험 일정 문의하기']};const key=randomUUID();
 media=await ok(A.cookie,`workspaces/${wp.id}/media`,'POST',payload,key);assert.equal(media.status,'succeeded');assert.equal(media.manifest.derived_status,'draft');assert.equal(media.manifest.files.length,2);assert(!JSON.stringify(media).includes('object_key'));assert(media.manifest.files.every((f:any)=>!f.key));assert.equal((await ok(A.cookie,`workspaces/${wp.id}/media`,'POST',payload,key)).id,media.id);
 const response=await handle(new Request(origin+`/api/workspaces/${wp.id}/media/${media.id}/download?file=square.png`,{headers:{cookie:A.cookie}}));assert.equal(response.status,200);const png=new Uint8Array(await response.arrayBuffer());const metadata=await sharp(png).metadata();assert.equal(metadata.width,1080);assert.equal(metadata.height,1080);await writeFile('docs/p1-card-example.png',png);
 assert.equal((await call(A.cookie,`workspaces/${wp.id}/media`,'POST',{...payload,scenes:['매출 50% 증가',...payload.scenes.slice(1)]},randomUUID())).status,400);
 assert.equal((await call(A.cookie,`workspaces/${wp.id}/media/${media.id}/download?file=../../secret`)).status,404);
});
await test('P1 렌더 실패 상태·재시도·9초 영상 및 SRT 검증',async()=>{
 const payload={content_id:cp.id,version:3,asset_id:photo.id,kind:'video',scenes:['공원구 입문 체험 · 예시','장비 대여와 기본 규칙 안내','체험 일정 문의하기']};
 process.env.FFMPEG_PATH='/nonexistent/ffmpeg';const badKey=randomUUID();assert.equal((await call(A.cookie,`workspaces/${wp.id}/media`,'POST',payload,badKey)).status,503);delete process.env.FFMPEG_PATH;
 assert.equal((await call(A.cookie,`workspaces/${wp.id}/media`,'POST',payload,badKey)).status,409);
 const video=await ok(A.cookie,`workspaces/${wp.id}/media`,'POST',payload,randomUUID());assert.equal(video.manifest.files.length,4);
 const srt=await ok(A.cookie,`workspaces/${wp.id}/media/${video.id}/download?file=subtitles.srt`);assert(srt.includes('00:00:06,000 --> 00:00:09,000'));assert(srt.includes(payload.scenes[2]));
 const response=await handle(new Request(origin+`/api/workspaces/${wp.id}/media/${video.id}/download?file=video.mp4`,{headers:{cookie:A.cookie}}));assert.equal(response.status,200);await writeFile('docs/p1-video-example.mp4',new Uint8Array(await response.arrayBuffer()));
 const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const {stdout}=await promisify(execFile)('ffprobe',['-v','error','-show_entries','format=duration:stream=width,height,codec_name','-of','json','docs/p1-video-example.mp4']);const probe=JSON.parse(stdout);assert.equal(Number(probe.format.duration),9);assert.equal(probe.streams[0].width,720);assert.equal(probe.streams[0].height,1280);assert.equal(probe.streams[0].codec_name,'h264');
});
await test('P1 미디어·승인·재사용의 작업공간 격리 및 viewer 제한',async()=>{
 const db=await getDb();await db.query('DELETE FROM membership WHERE workspace_id=$1 AND user_id=$2',[wp.id,B.userId]);
 for(const route of [`media/${media.id}`,`media/${media.id}/download?file=square.png`,`contents/${cp.id}`])assert.equal((await call(B.cookie,`workspaces/${wp.id}/`+route)).status,404);
 assert.equal((await call(B.cookie,`workspaces/${wb.id}/media/${media.id}`)).status,404);
 assert.equal((await call(B.cookie,`workspaces/${wp.id}/contents/${cp.id}/reuse`,'POST',{version:3})).status,404);
 await db.query("INSERT INTO membership(workspace_id,user_id,role) VALUES($1,$2,'viewer')",[wp.id,B.userId]);
 assert.equal((await call(B.cookie,`workspaces/${wp.id}/media/${media.id}`)).status,200);
 for(const action of ['review','reuse'])assert.equal((await call(B.cookie,`workspaces/${wp.id}/contents/${cp.id}/${action}`,'POST',{version:3,action:'submit'})).status,403);
 assert.equal((await call(B.cookie,`workspaces/${wp.id}/media`,'POST',{})).status,403);
 await db.query('DELETE FROM membership WHERE workspace_id=$1 AND user_id=$2',[wp.id,B.userId]);
});
await test('로그아웃 후 기존 세션 무효화',async()=>{const auth=await getAuth();const r=await auth.handler(new Request(origin+'/api/auth/sign-out',{method:'POST',headers:{cookie:B.cookie,origin,'Content-Type':'application/json'},body:'{}'}));assert.equal(r.status,200);assert.equal((await call(B.cookie,'me')).status,401)});
await writeFile('docs/acceptance-results.json',JSON.stringify({date:new Date().toISOString(),engine:'server-side persistent PostgreSQL/PGlite',tests:results,notRun:['Mobile browser end-to-end','External PostgreSQL/S3 credentials','Paid AI provider quality']},null,2)+'\n');
console.log(`${results.length} acceptance tests passed`);process.exit(0);
